name: Test Assembly

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build and run all
        run: |
          gcc main.c sumOfPowers.s compareAges.s findPaymentsSum.s findSalariesSum.s -o a.out
          ./a.out